language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew clean test

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

